version: '3'

tasks:
  build-agent:
    cmds:
      - task: build-static-ui
      - CGO_ENABLED=0 go build -o algomon-agent ./cmd/agent

  run-agent:
    cmds:
      - task: build-agent
      - sh -c ./algomon-agent

  build-static-ui:
    cmds:
      - cd ui/dashboard && bun run build
      - rm -rf cmd/agent/static && mkdir cmd/agent/static
      - cp -r ui/dashboard/build/* cmd/agent/static/
      
